### ISSUE TITLE
Undefined method 'validateDatabaseSchema' in app_database.dart

### ISSUE THREAD

**Issue by andydoc** [r1n1os/drift_local_database_example_using_drift_file#1]
Line 45 in lib/data/local_database/app_database.dart is giving me an error:
> The method 'validateDatabaseSchema' isn't defined for the type 'AppDatabase'.
> Try correcting the name to the name of an existing method, or defining a method named 'validateDatabaseSchema'.

Any ideas?

my database.dart file is:
```
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:flutter/foundation.dart';

part 'database.g.dart';

@DriftDatabase(
  include: {'tables.drift'},
)
class AppDatabase extends _$AppDatabase {

  static AppDatabase instance() => AppDatabase();

  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: (Migrator m, int from, int to) async {
          if (from < 2) {}
      },
      beforeOpen: (details) async {
          if (kDebugMode) {
          await validateDatabaseSchema();
        };
      },
    );
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationCacheDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
```
pubspec.yaml includes:
```
dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02
  cupertino_icons: ^1.0.6
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
```
